#生产环境 一体机
njmsc:
  logback:
    path: d:\\bpg\\njmsc\\logs
  data:
    save: true
    path: d:\\bpg\\njmsc\\datas
  db:
    address: 127.0.0.1:3306/nj_switch_cabinet
    username: root
    password: root
  redis:
    ip: 127.0.0.1

# 定时任务相关配置
scheduled:
  task:
    runable:
      global: true
      single:
        AmtechArresterRtuScheduled:
          collectAmtechArresterSerialData: false



# 日志
logging:
  level:
    root: info
    org:
      springframework:
        boot:
          autoconfigure: ERROR

eureka:
  instance:
    hostname: 127.0.0.1
    lease-renewal-interval-in-seconds: 20
    lease-expiration-duration-in-seconds: 60
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: 127.0.0.1:${server.port}
  client:
    service-url:
      defaultZone: http://127.0.0.1:18761/eureka

address:
  server: 127.0.0.1

